### ISSUE TITLE
Unable to lookup correct "kid"

### ISSUE THREAD

**Issue by LarryBarker** [okta/okta-jwt-verifier-php#40] opened 2020-02-13 04:06 UTC
Running into issues verifying JWT in a Laravel app again. This time, we are trying to verify the token as issued from Okta in our Laravel web app. I've followed a couple of tutorials from Okta ([https://developer.okta.com/blog/2019/01/15/crud-app-laravel-vue](https://developer.okta.com/blog/2019/01/15/crud-app-laravel-vue) and [https://developer.okta.com/blog/2019/09/05/laravel-authentication](https://developer.okta.com/blog/2019/09/05/laravel-authentication)) to get started. 

I can authenticate with Okta and sign in to the application. The challenge I'm having is when the user signs out of Okta, but not the Laravel application, they are obviously still authenticated in the Laravel application. This is problematic for our use cases and provides a less than ideal user experience.

I've posted some comments and questions in other places about this issue. See [Socialite middleware to check if authenticated](https://laracasts.com/discuss/channels/laravel/socialite-middleware-to-check-if-authenticated) and [my comments on the Laravel tutorial](http://disq.us/p/279zp93). 

So, what I have done is created a middleware from the Laravel/Vue tutorial and applied it to one of my routes for testing. Theoretically this middleware will use the stored token from Okta and verify it to see if it is still valid in order to process the request:

```
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Support\Facades\Auth;

class AuthenticateWithOkta
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        if ($this->isAuthorized($request)) {
            return $next($request);
        } else {
            return response('Unauthorized.', 401);
        }
    }

    public function isAuthorized($request)
    {
        if (!Auth::user()) {
            return false;
        }

        $user = Auth::user();
        
        if (!$user->token) {
            return false;
        }
        
        $token = $user->token;

        // Attempt authorization with the user token
        try {
            
            // Setup the JWT Verifier
            $jwtVerifier = (new \Okta\JwtVerifier\JwtVerifierBuilder())
                            ->setAdaptor(new \Okta\JwtVerifier\Adaptors\FirebasePhpJwt)
                            ->setAudience('api://default')
                            ->setClientId('0oa2twkr01nYOcz2O357')
                            ->setIssuer('https://dev-635281.okta.com/oauth2/default')
                            ->build();
                            
            // Verify the JWT for the authenticated user.
            $jwt = $jwtVerifier->verify($token);
            
        } catch (\Exception $e) {
            // You encountered an error, return a 401.
            dd($e->getMessage());
            return false;
        }

        return true;
    }
}
```

I had a similar issue verifying JWT with our API middleware a while back, and cannot remember what we did to resolve the issue. I do remember that we used [jwt.io](https://jwt.io) to compare the token's `kid` to the keys provided by the authorization server (https://{orgUrl}/oauth2/v1/keys). For example:

![image](https://user-images.githubusercontent.com/28734844/74400407-6e336b80-4de3-11ea-9c48-4703584e247f.png)

vs

```
{
"keys": [
{
...
"kid": "A8RUZjhiMa51sc3gKrn1sR2TE1WpHIPYeEeoGUUTyHE",
...
},
{
...
"kid": "cKuHnq8ou7Y7FqBf_auODmBf9y_M6bj35EdbxBYzKik",
...
}
]
}
```

As you can see, the `kid` do not match. Why this is I do not know. Any feedback is greatly appreciated!

References
#17
#33
[https://developer.okta.com/blog/2020/01/15/protecting-a-php-api-with-oauth](https://developer.okta.com/blog/2020/01/15/protecting-a-php-api-with-oauth)

**Comment by rjganesh** [comment] 2020-02-19 01:19
Team,
Can you please have a look at this, I am also facing the same issue

**Comment by DigitalManufacturingAMMS** [comment] 2020-03-06 14:10
I am also having this issue, and its holding up the project I am on.

**Comment by LarBearrr** [comment] 2020-03-07 02:53
The issue is due to the fact that Okta has their own authorization server which is used anytime you authenticate with an Okta hosted sign in page. Okta does not make the keys to their authorization server available. You will need to use a custom authorization server.

**Comment by rdkls** [comment] 2020-07-16 08:06
Pretty sure this is the same issue as https://github.com/okta/okta-jwt-verifier-php/issues/32

The default Okta (not your custom) auth server metadata response contains no `jwks_uri` element, yet the JWT verifier assumes it does

**Comment by bretterer** [comment] 2020-07-17 16:26
Internal Ref: OKTA-314097

**Comment by bretterer** [comment] 2020-08-07 18:44
This appears to be the same issue as @rdkls has mentioned.  

In PR #50 which has been merged into develop, we throw a domain exception if we can't find the jwks_uri from the metadata, which happens if you are using the Okta AS and not a custom authorization server.

I am going to close this as resolved, but if you feel this is not the case feel free to respond here or open a new issue.

**Closed by bretterer** 2020-08-07 18:44 UTC
